export const STATES = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alasca' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'Califórnia' },
  { value: 'NC', label: 'Carolina do Norte' },
  { value: 'SC', label: 'Carolina do Sul' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'ND', label: 'Dakota do Norte' },
  { value: 'SD', label: 'Dakota do Sul' },
  { value: 'DE', label: 'Delaware' },
  { value: 'DC', label: 'Distrito de Colúmbia' },
  { value: 'FL', label: 'Flórida' },
  { value: 'GA', label: 'Geórgia' },
  { value: 'HI', label: 'Havaí' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Luisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'Nova Hampshire' },
  { value: 'NJ', label: 'Nova Jersey' },
  { value: 'NY', label: 'Nova York' },
  { value: 'NM', label: 'Novo México' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pensilvânia' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virgínia' },
  { value: 'WV', label: 'Virgínia Ocidental' },
  { value: 'WA', label: 'Washington' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
] as const

export const PARTIES = [
  { value: '', label: 'Todos os partidos' },
  { value: 'Democratic', label: 'Democrata' },
  { value: 'Republican', label: 'Republicano' },
  { value: 'Independent', label: 'Independente' },
  { value: 'Nonpartisan', label: 'Sem filiação' },
  { value: 'Libertarian', label: 'Libertário' },
  { value: 'Progressive', label: 'Progressista' },
  { value: 'Green', label: 'Verde' },
] as const

const stateNames = new Map<string, string>(
  STATES.map(({ value, label }) => [value, label]),
)

export function getStateName(state: string) {
  return stateNames.get(state) ?? state
}
