/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/people/sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sincroniza pessoas de todos os estados
     * @description Percorre todas as páginas da OpenStates para os 50 estados e o Distrito de Colúmbia, respeita o limite de requisições da API externa e atualiza o cache PostgreSQL usando upsert. A operação pode levar vários minutos.
     */
    post: operations['syncAllPeople']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/people': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Lista pessoas do cache local
     * @description Retorna as pessoas persistidas no PostgreSQL sem realizar chamadas à OpenStates.
     */
    get: operations['listPeople']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  syncAllPeople: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Resumo da sincronização geral */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Quantidade de pessoas recebidas e persistidas */
            fetched: number
            /** @description Quantidade de estados e jurisdições sincronizados */
            states: number
          }
        }
      }
      /** @description Erro da aplicação */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Descrição do erro */
            message: string
          }
        }
      }
      /** @description Erro da aplicação */
      502: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Descrição do erro */
            message: string
          }
        }
      }
    }
  }
  listPeople: {
    parameters: {
      query: {
        state: string
        party?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Pessoas disponíveis no cache PostgreSQL */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Identificador da pessoa na OpenStates */
            id: string
            /** @description Nome completo */
            name: string
            /** @description Cargo político atual */
            role: string | null
            /** @description URL da foto, quando disponível */
            imageUrl: string | null
            /** @description Nome da jurisdição ou estado */
            state: string
            /** @description Partido político, quando disponível */
            party: string | null
          }[]
        }
      }
      /** @description Erro de validação da requisição */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Código HTTP */
            statusCode: number
            /** @description Código interno do Fastify */
            code: string
            /** @description Categoria do erro HTTP */
            error: string
            /** @description Detalhes da validação */
            message: string
          }
        }
      }
      /** @description Erro da aplicação */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description Descrição do erro */
            message: string
          }
        }
      }
    }
  }
}
